#
#

alias aliases="nano ~/.bash_aliases"

alias lmstudio="/opt/studio/studio.AppImage"


alias dormir="sh ~/.adormir.sh"


# some more ls aliases
alias l='ls -F'	# Modo corto
alias ll='ls -lFh'	# Modo lista
alias la='ls -AalFh'	# Modo lista muestra ocultos
alias li='ls -AalFhi'    # Modo lista muestra ocultos y su inode

alias casa='cd /mnt/DATOS/LINUX/c2mismo'

alias docu='cd $HOME/PROYECTOS/documentos'
alias arch='cd $HOME/PROYECTOS/archLinux'
alias dot='cd $HOME/PROYECTOS/dotfiles/'
alias cara='cd $HOME/PROYECTOS//caravan/'

# No usados
# alias box='cd $HOME/PROYECTOS/arduino/230box/'
# alias ardu='cd $HOME/PROYECTOS/arduino/ArduMan/'
# alias libs='cd $HOME/PROYECTOS/arduino/arduLibs/'
# alias info='cd $HOME/PROYECTOS/info/'


alias gpu='~/.gitpush.sh'

alias gst='~/.gitstatus.sh'

alias dirtemp='dirtemp=$(mktemp -dp /run/user/$UID) && chmod +t $dirtemp && echo $dirtemp && cd $dirtemp'


# ls -F
# @ significa enlace simbólico (o que el archivo tiene atributos extendidos)
# * significa ejecutable
# = significa zócalo
# | significa pipa nombrada
# > significa puerta
# / significa directorio

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'



